/**
 * channelRegistry.ts
 *
 * Reads channel-registry.json generated by scripts/fetch-channels.ts
 * at build time. Falls back to staticChannels if not yet generated.
 */

// Types defined inline (not imported from scripts/ to avoid ESM issues)
export interface ChannelEntry {
  id: string
  name: string
  countryCode: string
  countryName: string
  countrySlug: string
  countryFlag: string
  category: string
  language: string
  logo: string
  streamUrl: string
  tvgId: string
  website: string
}

interface ChannelRegistry {
  generatedAt: string
  totalChannels: number
  channels: ChannelEntry[]
}

// ── Load registry ─────────────────────────────────────────────────────────────

let _registry: ChannelRegistry | null = null

function loadRegistry(): ChannelRegistry {
  if (_registry) return _registry
  try {
    // Next.js resolves JSON imports at build time
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const data = require('./channel-registry.json') as ChannelRegistry
    _registry = data
    return data
  } catch {
    console.warn('[channelRegistry] channel-registry.json not found — run: npm run fetch-channels')
    _registry = { generatedAt: '', totalChannels: 0, channels: [] }
    return _registry
  }
}

// ── Public API ────────────────────────────────────────────────────────────────

export function getAllChannelEntries(): ChannelEntry[] {
  return loadRegistry().channels
}

export function getChannelEntryById(id: string): ChannelEntry | undefined {
  return loadRegistry().channels.find(c => c.id === id)
}

export function getChannelEntriesByCountry(countrySlug: string): ChannelEntry[] {
  return loadRegistry().channels.filter(c => c.countrySlug === countrySlug)
}

export function getChannelEntriesByCategory(category: string): ChannelEntry[] {
  return loadRegistry().channels.filter(
    c => c.category.toLowerCase() === category.toLowerCase()
  )
}

export function getAllChannelIds(): string[] {
  return loadRegistry().channels.map(c => c.id)
}

export function getTotalChannelCount(): number {
  return loadRegistry().totalChannels
}

export function getAllCategories(): string[] {
  const cats = new Set(loadRegistry().channels.map(c => c.category || 'General'))
  return Array.from(cats).sort()
}

export const CATEGORY_ICONS: Record<string, string> = {
  news: '📰', sports: '⚽', entertainment: '🎬', kids: '🧒',
  music: '🎵', documentary: '🎥', movies: '🎞️', lifestyle: '🌿',
  business: '📈', religious: '🕌', general: '📺',
}

export function getCategoryIcon(category: string): string {
  return CATEGORY_ICONS[category.toLowerCase()] ?? '📺'
}
